### ISSUE TITLE
TensorFlow Running

### ISSUE THREAD

**Issue by chrisjbaik** [paivaspol/EECS583#1]
Get TensorFlow running:

**Input**: sequence of variable length strings: `["cat", "dog", "meow"]`
**Output**: single value: `0.5`

**Comment by chrisjbaik** [comment]
Possibilities:

**RNN**
http://deeplearning.net/tutorial/lstm.html

**CNN**
http://emnlp2014.org/papers/pdf/EMNLP2014181.pdf
http://link.springer.com/chapter/10.1007/978-3-319-19644-2_60
http://disi.unitn.it/~severyn/papers/sigir-2015-short.pdf

**Comment by arquinn** [comment]
I got the valgrind script running on the SPEC benchmark, and I have a few things to report:

Valgrind only gets cache performance numbers for about 30 functions (I will add the specific functions to the repository later). This contradicts with Vaspol finding close to 91 functions in the source… I think Valgrind cuts off any functions that it don’t meet some threshold in number of times its been called, and I’ve lowered that function as much as possible, so I don’t think there is anything I can do. We also might think about inlining functions in our source representation so that we have more accurate source information for our neural network… more on that for our next meeting
Valgrind gives us a variety of numbers that we can take a look at creating. Namely, it does first level icache miss rate, last level icache miss rate, first level data cache miss rate, last level data cache miss rate and they have an assumption of a shared data and instruction last layer cache which they calculate results for as well. I’m suggesting that we basically have two separate data points. We can do last level icache miss rate and last level data cache miss rate. Again, I can explain more at our next meeting
- Andrew

**Comment by chrisjbaik** [comment]
Well, something's running with this commit: 1b0f7b0313165340ee05a9c9dd1b7317af2aec0b

**Comment by paivaspol** [comment]
@chrisjbaik nice! :+1: :+1:
